# Generated by Django 5.0.2 on 2024-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='answer_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
