# Generated by Django 5.0.2 on 2024-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioners', '0002_answer_img_question_sub_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=10, null=True)),
                ('questions', models.ManyToManyField(blank=True, null=True, to='questioners.question')),
            ],
        ),
    ]
