# Generated by Django 5.0.2 on 2024-02-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questioners', '0003_sets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sets',
            options={'verbose_name': 'Sets', 'verbose_name_plural': 'Sets'},
        ),
    ]
