# Generated by Django 5.0.2 on 2024-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioners', '0004_alter_sets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
