# Generated by Django 5.0.2 on 2024-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioners', '0006_alter_quizhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_frame',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
